# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: University
  items:
    - label: 'What year are you?'
      link: '/university/what-year-are-you'
    - label: 'Application process'
      link: '/university/application-process'
    - label: 'Increasing the odds'
      link: '/university/increasing-the-odds'
    - label: 'Opportunities for students'
      link: '/university/opportunities-for-students'
- label: Specific to KAIST
  items: 
    - label: 'Work permit'
      link: '/for-kaist/work-permit'
    - label: 'Getting credits for internship'
      link: '/for-kaist/substituting-research-credits'
    - label: 'Data Science Track at KAIST'
      link: '/for-kaist/data-science-track-at-kaist'